# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'citizenconnect' do
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'Popover'
pod 'ObjectMapper', '~> 3.1'
pod 'SDWebImage', '~> 4.0'
pod 'AlamofireImage', '~> 3.3'
pod 'Toast-Swift', '~> 3.0.1'
pod 'MBCircularProgressBar'
  # Pods for citizenconnect

  target 'citizenconnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'citizenconnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
