# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'citizenconnect' do
pod 'Firebase/Core'
pod 'Firebase/Database'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'ObjectMapper', '~> 3.1'
pod 'SDWebImage', '~> 4.0'
  # Pods for citizenconnect

  target 'citizenconnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'citizenconnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
